import {
  angleToRadian,
  CanvasWidgetRectboxConfig,
  CanvasWidgetStyleConfig,
  Point,
  Position,
  rotatePoint,
  SnowflakeId,
  TransformConfig,
} from "../other/Utils";
import type { CanvasContainerWidget } from "./CanvasContainerWidget";
import { CanvasPainter } from "./CanvasPainter";
import { BBox } from "../VerbalRTree";

export enum CanvasWidgetTypeEnum {
  Holder = "HOLDER",
  Layer = "LAYER",
  Rectangle = "RECTANGLE",
  Ellipse = "ELLIPSE",
  Line = "LINE",
  CustomShape = "CUSTOM",
  Group = "GROUP",
}

export interface CanvasWidgetEvent {
  eventType: string;
  targetWidget: CanvasWidget | null;
  currentWidget: CanvasWidget | null;
  nativeEvent?: MouseEvent;
  point?: Point;
  enableBubble: boolean;
  stopPropagation: () => void;
}

export interface CanvasWidgetBaseAttrConfig {
  position?: Position;
  scaleX?: number;
  scaleY?: number;
  rotation?: number;
  style?: CanvasWidgetStyleConfig;
}

export interface CanvasWidgetSundryConfig {
  visible: boolean;
  enableAutoPaint: boolean;
  enableEvent: boolean;
}

export enum CanvasWidgetEventTypeEnum {
  PointerMove = "pointermove",
  PointerDown = "pointerdown",
  PointerUp = "pointerup",
  OnClick = "onclick",
  Hover = "hover",
  HoverOut = "hoverout",
  OnChange = "onchange",
}

type CanvasWidgetEventHandlerType = (event: CanvasWidgetEvent) => void;

export abstract class CanvasWidget {
  // The internally unique ID generated by the snowflake algorithm
  private id: string;

  // Geometric position
  private position: Position = { x: 0, y: 0 };

  // Geometric shape center point
  private centerPoint: Point = { x: 0, y: 0 };

  private transformConfig: TransformConfig = {
    scaleX: 1,
    scaleY: 1,
    rotation: 0,
  };

  private bBoxConfig: CanvasWidgetRectboxConfig = {
    x: 0,
    y: 0,
    width: 0,
    height: 0,
  };

  private worldBboxCache: BBox | null = null;

  private eventConfig: Map<string, CanvasWidgetEventHandlerType[]> = new Map();

  private sundryConfig: CanvasWidgetSundryConfig = {
    visible: true,
    enableAutoPaint: true,
    enableEvent: true,
  };

  private styleConfig: CanvasWidgetStyleConfig = {};

  private parent: CanvasContainerWidget | null = null;

  private static idGenerator = new SnowflakeId();

  constructor(config: CanvasWidgetBaseAttrConfig) {
    this.id = CanvasWidget.idGenerator.generate();
    this.initBaseAttrConfig(config);
  }

  private initBaseAttrConfig(config: CanvasWidgetBaseAttrConfig) {
    this.position = config.position
      ? Object.assign({}, config.position)
      : { x: 0, y: 0 };
    this.transformConfig.scaleX = config.scaleX ?? 1;
    this.transformConfig.scaleY = config.scaleY ?? 1;
    this.transformConfig.rotation = config.rotation ?? 0;
    this.styleConfig = config.style ? Object.assign({}, config.style) : {};
  }

  protected calculateCenterPoint() {}

  protected calculateBboxConfig() {}

  // Getter And Setter
  public getId(): string {
    return this.id;
  }

  public getPosition(): Position {
    return Object.assign({}, this.position);
  }

  public getScaleX(): number {
    return this.transformConfig.scaleX;
  }

  public getScaleY(): number {
    return this.transformConfig.scaleY;
  }

  public getRotation(): number {
    return this.transformConfig.rotation;
  }

  public getCenterPoint(): Point {
    return Object.assign({}, this.centerPoint);
  }

  public getBboxConfig(): CanvasWidgetRectboxConfig {
    return Object.assign({}, this.bBoxConfig);
  }

  public getStyleConfig() {
    return Object.assign({}, this.styleConfig);
  }

  public getBboxVertexList(): Point[] {
    const maxX = this.bBoxConfig.x + this.bBoxConfig.width;
    const maxY = this.bBoxConfig.y + this.bBoxConfig.height;
    return [
      { x: this.bBoxConfig.x, y: this.bBoxConfig.y },
      { x: maxX, y: this.bBoxConfig.y },
      { x: maxX, y: maxY },
      { x: this.bBoxConfig.x, y: maxY },
    ];
  }

  public getClientBboxVertexList(): Point[] {
    const local = this.getLocalBboxVertexList();
    return local.map((vertex) => this.localToParentPoint(vertex));
  }

  protected getLocalBboxVertexList(): Point[] {
    return [];
  }

  public getWorldBbox(): BBox {
    if (this.worldBboxCache) return this.worldBboxCache;
    const vertices = this.getClientBboxVertexList();
    let bbox: BBox;
    if (vertices.length === 0) {
      bbox = { minX: 0, minY: 0, maxX: 0, maxY: 0 };
    } else {
      let minX = Infinity;
      let minY = Infinity;
      let maxX = -Infinity;
      let maxY = -Infinity;
      for (const vertex of vertices) {
        minX = Math.min(minX, vertex.x);
        minY = Math.min(minY, vertex.y);
        maxX = Math.max(maxX, vertex.x);
        maxY = Math.max(maxY, vertex.y);
      }
      bbox = { minX, minY, maxX, maxY };
    }
    this.worldBboxCache = bbox;
    return bbox;
  }

  protected invalidateWorldBbox() {
    this.worldBboxCache = null;
    if (this.parent) this.parent.invalidateWorldBbox();
  }

  public getTransformConfig(): TransformConfig {
    return Object.assign({}, this.transformConfig);
  }

  public getWidgetType(): string {
    return "UNKNOWN";
  }

  public getVisible() {
    return this.sundryConfig.visible;
  }

  public getEnableAutoPaint() {
    return this.sundryConfig.enableAutoPaint;
  }

  public setVisible(visible: boolean) {
    this.sundryConfig.visible = visible;
  }

  public setEnableAutoPaint(enableAutoPaint: boolean) {
    this.sundryConfig.enableAutoPaint = enableAutoPaint;
  }

  public getEnableEvent() {
    return this.sundryConfig.enableEvent;
  }

  public setEnableEvent(enableEvent: boolean) {
    this.sundryConfig.enableEvent = enableEvent;
  }

  public getParent() {
    return this.parent;
  }

  protected setCenterPoint(newCenterPoint: Point) {
    this.centerPoint = Object.assign({}, newCenterPoint);
  }

  protected setBboxConfig(newBboxConfig: CanvasWidgetRectboxConfig) {
    this.bBoxConfig = Object.assign({}, newBboxConfig);
  }

  public getLevelIndex() {
    if (!this.parent) return -1;
    const children = this.parent.getChildren();
    return children.findIndex((item) => item === this);
  }

  public levelUp() {
    if (!this.parent) return;
    const children = this.parent.getChildren();
    const index = children.findIndex((item) => item === this);
    if (index === -1 || index >= children.length - 1) return;
    [children[index], children[index + 1]] = [children[index + 1], children[index]];
    this.emitEvent(CanvasWidgetEventTypeEnum.OnChange);
  }

  public levelDown() {
    if (!this.parent) return;
    const children = this.parent.getChildren();
    const index = children.findIndex((item) => item === this);
    if (index <= 0) return;
    [children[index], children[index - 1]] = [children[index - 1], children[index]];
    this.emitEvent(CanvasWidgetEventTypeEnum.OnChange);
  }

  public getLayer(): CanvasWidget | null {
    let cur: CanvasWidget | null = this;
    while (cur) {
      if (cur.getWidgetType() === CanvasWidgetTypeEnum.Layer) return cur;
      cur = cur.parent;
    }
    return null;
  }

  // =====================================================

  // update function
  protected updatePosition(newPosition: Position) {
    const deltaX = newPosition.x - this.position.x;
    const deltaY = newPosition.y - this.position.y;
    const newCenterPoint: Point = {
      x: this.centerPoint.x + deltaX,
      y: this.centerPoint.y + deltaY,
    };
    const newBboxConfig: CanvasWidgetRectboxConfig = {
      x: this.bBoxConfig.x + deltaX,
      y: this.bBoxConfig.y + deltaY,
      width: this.bBoxConfig.width,
      height: this.bBoxConfig.height,
    };
    this.position = { ...newPosition };
    this.centerPoint = newCenterPoint;
    this.bBoxConfig = newBboxConfig;
  }

  public updateTransformConfig(newTransformConfig: Partial<TransformConfig>) {
    this.transformConfig = Object.assign(
      {},
      this.transformConfig,
      newTransformConfig,
    );
    this.invalidateWorldBbox();
  }

  public remove() {
    if (!this.parent) return;
    const oldParent = this.parent;
    const children = oldParent.getChildren();
    const level_index = children.findIndex((item) => item === this);
    children.splice(level_index, 1);
    this.parent = null;
    this.invalidateWorldBbox();
    oldParent.invalidateWorldBbox();
    this.emitEvent(CanvasWidgetEventTypeEnum.OnChange);
  }

  public place2Parent(newParent: CanvasContainerWidget | null) {
    if (this.parent) this.remove();
    if (!newParent) return;
    const children = newParent.getChildren();
    children.push(this);
    this.parent = newParent;
    this.invalidateWorldBbox();
    this.emitEvent(CanvasWidgetEventTypeEnum.OnChange);
  }

  // Event related
  public addEvent(
    eventType: CanvasWidgetEventTypeEnum,
    handler: CanvasWidgetEventHandlerType,
  ) {
    const handlerList = this.eventConfig.get(eventType) ?? [];
    const res = handlerList.find((item) => item === handler);
    if (res) return;
    handlerList.push(handler);
    this.eventConfig.set(eventType, handlerList);
  }

  public clearEvent(eventType: CanvasWidgetEventTypeEnum) {
    this.eventConfig.delete(eventType);
  }

  public removeEvent(
    eventType: CanvasWidgetEventTypeEnum,
    handler?: CanvasWidgetEventHandlerType,
  ) {
    if (!handler) {
      this.clearEvent(eventType);
      return;
    }
    const handlerList = this.eventConfig.get(eventType);
    if (!handlerList) return;
    this.eventConfig.set(
      eventType,
      handlerList.filter((item) => item !== handler),
    );
  }

  public emitEvent(
    eventType: CanvasWidgetEventTypeEnum,
    nativeEvent?: MouseEvent,
    point?: Point,
  ) {
    if (eventType === CanvasWidgetEventTypeEnum.OnChange) {
      if (!this.sundryConfig.enableAutoPaint) return;
    } else if (!this.sundryConfig.enableEvent) {
      return;
    }
    const canvasWidgetEvent: CanvasWidgetEvent = {
      eventType,
      targetWidget: this,
      currentWidget: this,
      nativeEvent,
      point,
      enableBubble: true,
      stopPropagation: () => {
        canvasWidgetEvent.enableBubble = false;
      },
    };
    this.emitBubbleEvent(canvasWidgetEvent);
  }

  private emitBubbleEvent(canvasWidgetEvent: CanvasWidgetEvent) {
    canvasWidgetEvent.currentWidget = this;
    const handlerList = this.eventConfig.get(canvasWidgetEvent.eventType);
    if (handlerList) {
      for (const handler of handlerList) {
        handler.call(this, canvasWidgetEvent);
        if (!canvasWidgetEvent.enableBubble) return;
      }
    }
    if (this.parent) this.parent.emitBubbleEvent(canvasWidgetEvent);
  }

  // =====================================================

  public isPointInShape(point: Point): boolean {
    if (!this.sundryConfig.visible || !this.sundryConfig.enableEvent) return false;
    const localPoint = this.parentToLocalPoint(point);
    return this.subIsPointInShape(localPoint);
  }

  protected subIsPointInShape(point: Point): boolean {
    return false;
  }

  public hitTest(point: Point): CanvasWidget | null {
    if (!this.sundryConfig.visible || !this.sundryConfig.enableEvent) return null;
    const localPoint = this.parentToLocalPoint(point);
    return this.subHitTest(localPoint);
  }

  protected subHitTest(point: Point): CanvasWidget | null {
    return this.subIsPointInShape(point) ? this : null;
  }

  public paint(canvasPainter: CanvasPainter): void {
    if (!this.sundryConfig.visible || this.styleConfig.globalAlpha === 0)
      return;
    canvasPainter.save();
    canvasPainter.updateStyle(this.styleConfig);
    this.applyTransform(canvasPainter);
    this.subPaint(canvasPainter);
    canvasPainter.restore();
  }

  // M = T(position)·T(offset)·R(rotation)·S(scale)·T(-offset)，offset = centerPoint - position
  private applyTransform(canvasPainter: CanvasPainter) {
    const { scaleX, scaleY, rotation } = this.transformConfig;
    const radian = angleToRadian(rotation);
    const cos = Math.cos(radian);
    const sin = Math.sin(radian);
    const ox = this.centerPoint.x - this.position.x;
    const oy = this.centerPoint.y - this.position.y;
    canvasPainter.transform(
      cos * scaleX,
      sin * scaleX,
      -sin * scaleY,
      cos * scaleY,
      this.position.x + ox * (1 - cos * scaleX) + sin * scaleY * oy,
      this.position.y + oy * (1 - cos * scaleY) - sin * scaleX * ox,
    );
  }

  private localToParentPoint(point: Point): Point {
    const { scaleX, scaleY, rotation } = this.transformConfig;
    const radian = angleToRadian(rotation);
    const cos = Math.cos(radian);
    const sin = Math.sin(radian);
    const ox = this.centerPoint.x - this.position.x;
    const oy = this.centerPoint.y - this.position.y;
    const a = cos * scaleX;
    const b = sin * scaleX;
    const c = -sin * scaleY;
    const d = cos * scaleY;
    const e = this.position.x + ox * (1 - a) - c * oy;
    const f = this.position.y + oy * (1 - d) - b * ox;
    return {
      x: a * point.x + c * point.y + e,
      y: b * point.x + d * point.y + f,
    };
  }

  private parentToLocalPoint(point: Point): Point {
    const { scaleX, scaleY, rotation } = this.transformConfig;
    const sx = scaleX !== 0 ? scaleX : 1;
    const sy = scaleY !== 0 ? scaleY : 1;
    const ox = this.centerPoint.x - this.position.x;
    const oy = this.centerPoint.y - this.position.y;
    let q = { x: point.x - this.position.x, y: point.y - this.position.y };
    q = { x: q.x - ox, y: q.y - oy };
    q = rotatePoint(q, { x: 0, y: 0 }, -rotation);
    q = { x: q.x / sx, y: q.y / sy };
    return { x: q.x + ox, y: q.y + oy };
  }

  protected abstract subPaint(canvasPainter: CanvasPainter): void;

  public updateAttrConfig<T extends CanvasWidgetBaseAttrConfig>(
    newAttrConfig: T,
  ) {
    if (newAttrConfig.position !== undefined)
      this.updatePosition(newAttrConfig.position);

    if (newAttrConfig.scaleX !== undefined)
      this.transformConfig.scaleX = newAttrConfig.scaleX;

    if (newAttrConfig.scaleY !== undefined)
      this.transformConfig.scaleY = newAttrConfig.scaleY;

    if (newAttrConfig.rotation !== undefined)
      this.transformConfig.rotation = newAttrConfig.rotation;

    if (newAttrConfig.style !== undefined)
      this.styleConfig = Object.assign({}, this.styleConfig, newAttrConfig.style);

    this.subUpdateAttr(newAttrConfig);
    this.invalidateWorldBbox();
    this.emitEvent(CanvasWidgetEventTypeEnum.OnChange);
  }

  protected subUpdateAttr<T extends CanvasWidgetBaseAttrConfig>(
    newAttrConfig: T,
  ) {}
}
