import {
  CanvasWidgetRectboxConfig,
  CanvasWidgetStyleConfig,
  Point,
  Position,
  rotatePoint,
  SnowflakeId,
  TransformConfig,
} from "../other/Utils";
import type { CanvasContainerWidget } from "./CanvasContainerWidget";
import { CanvasPainter } from "./CanvasPainter";

export enum CanvasWidgetTypeEnum {
  Holder = "HOLDER",
  Layer = "LAYER",
  Rectangle = "RECTANGLE",
  Ellipse = "ELLIPSE",
  Line = "LINE",
}

export interface CanvasWidgetEvent {
  eventType: string;
  targetWidget: CanvasWidget | null;
  currentWidget: CanvasWidget | null;
  nativeEvent?: MouseEvent;
  enableBubble: boolean;
}

export interface CanvasWidgetBaseAttrConfig {
  position?: Position;
  scaleX?: number;
  scaleY?: number;
  rotation?: number;
  style?: CanvasWidgetStyleConfig;
}

export interface CanvasWidgetSundryConfig {
  visible: boolean;
  enableAutoPaint: boolean;
  enableEvent: boolean;
}

export enum CanvasWidgetEventTypeEnum {
  PointerMove = "pointermove",
  PointerDown = "pointerdown",
  PointerUp = "pointerup",
  OnClick = "onclick",
  Hover = "hover",
  OnChange = "onchange",
}

type CanvasWidgetEventHandlerType = (event: CanvasWidgetEvent) => void;

export abstract class CanvasWidget {
  // The internally unique ID generated by the snowflake algorithm
  private id: number;

  // Geometric position
  private position: Position = { x: 0, y: 0 };

  // Geometric shape center point
  private centerPoint: Point = { x: 0, y: 0 };

  private transformConfig: TransformConfig = {
    scaleX: 1,
    scaleY: 1,
    rotation: 0,
  };

  private bBoxConfig: CanvasWidgetRectboxConfig = {
    x: 0,
    y: 0,
    width: 0,
    height: 0,
  };

  private eventConfig: Map<string, CanvasWidgetEventHandlerType[]> = new Map();

  private sundryConfig: CanvasWidgetSundryConfig = {
    visible: true,
    enableAutoPaint: true,
    enableEvent: true,
  };

  private styleConfig: CanvasWidgetStyleConfig = {};

  private parent: CanvasContainerWidget | null = null;

  private static idGenerator = new SnowflakeId();

  constructor(config: CanvasWidgetBaseAttrConfig) {
    this.id = CanvasWidget.idGenerator.generate();
    this.initBaseAttrConfig(config);
  }

  private initBaseAttrConfig(config: CanvasWidgetBaseAttrConfig) {
    this.position = config.position
      ? Object.assign({}, config.position)
      : { x: 0, y: 0 };
    this.transformConfig.scaleX = config.scaleX ?? 1;
    this.transformConfig.scaleY = config.scaleY ?? 1;
    this.transformConfig.rotation = config.rotation ?? 0;
    this.styleConfig = config.style ? Object.assign({}, config.style) : {};
  }

  protected calculateCenterPoint() {}

  protected calculateBboxConfig() {}

  // Getter And Setter
  public getId(): number {
    return this.id;
  }

  public getPosition(): Position {
    return Object.assign({}, this.position);
  }

  public getScaleX(): number {
    return this.transformConfig.scaleX;
  }

  public getScaleY(): number {
    return this.transformConfig.scaleY;
  }

  public getRotation(): number {
    return this.transformConfig.rotation;
  }

  public getCenterPoint(): Point {
    return Object.assign({}, this.centerPoint);
  }

  public getBboxConfig(): CanvasWidgetRectboxConfig {
    return Object.assign({}, this.bBoxConfig);
  }

  public getStyleConfig() {
    return Object.assign({}, this, this.styleConfig);
  }

  public getBboxVertexList(): Point[] {
    const maxX = this.bBoxConfig.x + this.bBoxConfig.width;
    const maxY = this.bBoxConfig.y + this.bBoxConfig.height;
    return [
      { x: this.bBoxConfig.x, y: this.bBoxConfig.y },
      { x: maxX, y: this.bBoxConfig.y },
      { x: maxX, y: maxY },
      { x: this.bBoxConfig.x, y: maxY },
    ];
  }

  public getClientBboxVertexList(): Point[] {
    if (this.transformConfig.rotation === 0) return this.getBboxVertexList();
    const geoBboxVertexList = this.getBboxVertexList();
    const clientBboxVertexList = [];
    for (const vertex of geoBboxVertexList) {
      clientBboxVertexList.push(
        rotatePoint(vertex, this.centerPoint, this.transformConfig.rotation),
      );
    }
    return clientBboxVertexList;
  }

  public getTransformConfig(): TransformConfig {
    return Object.assign({}, this.transformConfig);
  }

  public getWidgetType(): string {
    return "UNKNOWN";
  }

  public getVisible() {
    return this.sundryConfig.visible;
  }

  public getEnableAutoPaint() {
    return this.sundryConfig.enableAutoPaint;
  }

  public setVisible(visible: boolean) {
    this.sundryConfig.visible = visible;
  }

  public setEnableAutoPaint(enableAutoPaint: boolean) {
    this.sundryConfig.enableAutoPaint = enableAutoPaint;
  }

  public getEnableEvent() {
    return this.sundryConfig.enableEvent;
  }

  public setEnableEvent(enableEvent: boolean) {
    this.sundryConfig.enableEvent = enableEvent;
  }

  public getParent() {
    return this.parent;
  }

  protected setCenterPoint(newCenterPoint: Point) {
    this.centerPoint = Object.assign({}, newCenterPoint);
  }

  protected setBboxConfig(newBboxConfig: CanvasWidgetRectboxConfig) {
    this.bBoxConfig = Object.assign({}, newBboxConfig);
  }

  public getLevelIndex() {
    if (!this.parent) return -1;
    const children = this.parent.getChildren();
    return children.findIndex((item) => item === this);
  }

  public getLayer(): CanvasWidget | null {
    let cur: CanvasWidget | null = this;
    while (cur && cur.parent) cur = cur.parent;
    if (cur && cur.getWidgetType() === CanvasWidgetTypeEnum.Layer) return cur;
    return null;
  }

  // =====================================================

  // update function
  protected updatePosition(newPosition: Position) {
    const deltaX = newPosition.x - this.position.x;
    const deltaY = newPosition.y - this.position.y;
    const newCenterPoint: Point = {
      x: this.centerPoint.x + deltaX,
      y: this.centerPoint.y + deltaY,
    };
    const newBboxConfig: CanvasWidgetRectboxConfig = {
      x: this.bBoxConfig.x + deltaX,
      y: this.bBoxConfig.y + deltaY,
      width: this.bBoxConfig.width,
      height: this.bBoxConfig.height,
    };
    this.position = { ...newPosition };
    this.centerPoint = newCenterPoint;
    this.bBoxConfig = newBboxConfig;
  }

  public updateTransformConfig(newTransformConfig: Partial<TransformConfig>) {
    this.transformConfig = Object.assign(
      {},
      this.transformConfig,
      newTransformConfig,
    );
  }

  public remove() {
    if (!this.parent) return;
    const children = this.parent.getChildren();
    const level_index = children.findIndex((item) => item === this);
    children.splice(level_index, 1);
    this.parent = null;
    this.emitEvent(CanvasWidgetEventTypeEnum.OnChange);
  }

  public place2Parent(newParent: CanvasContainerWidget | null) {
    if (this.parent) this.remove();
    if (!newParent) return;
    const children = newParent.getChildren();
    children.push(this);
    this.parent = newParent;
    this.emitEvent(CanvasWidgetEventTypeEnum.OnChange);
  }

  // Event related
  public addEvent(
    eventType: CanvasWidgetEventTypeEnum,
    handler: CanvasWidgetEventHandlerType,
  ) {
    const handlerList = this.eventConfig.get(eventType) ?? [];
    const res = handlerList.find((item) => item === handler);
    if (res) return;
    handlerList.push(handler);
    this.eventConfig.set(eventType, handlerList);
  }

  public clearEvent(eventType: CanvasWidgetEventTypeEnum) {
    this.eventConfig.delete(eventType);
  }

  public removeEvent(
    eventType: CanvasWidgetEventTypeEnum,
    handler?: CanvasWidgetEventHandlerType,
  ) {
    if (!handler) {
      this.clearEvent(eventType);
      return;
    }
    const handlerList = this.eventConfig.get(eventType);
    if (!handlerList) return;
    this.eventConfig.set(
      eventType,
      handlerList.filter((item) => item !== handler),
    );
  }

  public emitEvent(
    eventType: CanvasWidgetEventTypeEnum,
    nativeEvent?: MouseEvent,
  ) {
    if (!this.sundryConfig.enableEvent) return;
    this.emitBubbleEvent({
      eventType,
      targetWidget: this,
      currentWidget: this,
      nativeEvent,
      enableBubble: true,
    });
  }

  private emitBubbleEvent(canvasWidgetEvent: CanvasWidgetEvent) {
    canvasWidgetEvent.currentWidget = this;
    const handlerList = this.eventConfig.get(canvasWidgetEvent.eventType);
    if (handlerList) {
      for (const handler of handlerList) {
        handler.call(this, canvasWidgetEvent);
        if (!canvasWidgetEvent.enableBubble) return;
      }
    }
    if (this.parent) this.parent.emitBubbleEvent(canvasWidgetEvent);
  }

  // =====================================================

  public isPointInShape(point: Point): boolean {
    return false;
  }

  public paint(canvasPainter: CanvasPainter): void {
    if (!this.sundryConfig.visible || this.styleConfig.globalAlpha === 0)
      return;
    canvasPainter.save();
    canvasPainter.updateStyle(this.styleConfig);
    canvasPainter.translate(this.position.x, this.position.y);
    canvasPainter.scale(
      this.transformConfig.scaleX,
      this.transformConfig.scaleY,
    );
    canvasPainter.translate(-this.position.x, -this.position.y);
    canvasPainter.translate(this.centerPoint.x, this.centerPoint.y);
    canvasPainter.rotate(this.transformConfig.rotation);
    canvasPainter.translate(-this.centerPoint.x, -this.centerPoint.y);
    this.subPaint(canvasPainter);
    canvasPainter.restore();
  }

  protected abstract subPaint(canvasPainter: CanvasPainter): void;

  public updateAttrConfig<T extends CanvasWidgetBaseAttrConfig>(
    newAttrConfig: T,
  ) {
    if (newAttrConfig.position) this.updatePosition(newAttrConfig.position);

    if (newAttrConfig.scaleX)
      this.transformConfig.scaleX = newAttrConfig.scaleX;

    if (newAttrConfig.scaleY)
      this.transformConfig.scaleY = newAttrConfig.scaleY;

    if (newAttrConfig.rotation)
      this.transformConfig.rotation = newAttrConfig.rotation;

    this.subUpdateAttr(newAttrConfig);

    if (this.sundryConfig.enableAutoPaint)
      this.emitEvent(CanvasWidgetEventTypeEnum.OnChange);
  }

  protected subUpdateAttr<T extends CanvasWidgetBaseAttrConfig>(
    newAttrConfig: T,
  ) {}
}
